CREATE DATABASE airflow_db;
CREATE DATABASE dytech;
CREATE USER dytech WITH PASSWORD 'pass' SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE airflow_db TO dytech;
-- GRANT ALL ON SCHEMA public TO ShopZada;
